apps/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.manage_staff_users, name='manage_staff_users'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.accounts import views
from django.contrib.auth import views as auth_view

urlpatterns = [
    # admin panels
    path('admin/', admin.site.urls),
    
    # authentication 
    path("register/", views.register , name='register'),
    path("profile/", views.profile , name='profile'),
    path("profile/manage_staff_users/", include("apps.accounts.urls"), name="manage_staff_users"),
    path("profile/update", views.profile_update , name='profile_update'),
    path('profile/update/username/', views.profile_update_username, name='profile_update_username'),
    path('email_update/', views.email_update, name='email_update'),
    path("login/", views.CustomLoginView.as_view(template_name='accounts/authentication/login.html'), name='login'),
    path("logout/", auth_view.LogoutView.as_view(template_name='accounts/authentication/logout.html'), name='logout'),
    
    # reset password
    path('reset_password/',auth_view.PasswordResetView.as_view(template_name='accounts/password_reset/reset_password.html'),name='reset_password'),
    path('reset_password_sent/',auth_view.PasswordResetDoneView.as_view(template_name='accounts/password_reset/reset_password_sent.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_view.PasswordResetConfirmView.as_view(template_name='accounts/password_reset/reset_password_confirm.html'),name='password_reset_confirm'),
    path('reset_password_complete/',auth_view.PasswordResetCompleteView.as_view(template_name='accounts/password_reset/reset_password_complete.html'),name='password_reset_complete'),

    # apps
    path("comments/", include("apps.comments.urls")),
    path("posts/", include("apps.posts.urls"), name='posts'),
    path("store/", include("apps.store.urls"), name='store'),
    path("courses/", include("apps.courses.urls"), name='courses_view'),
    path("about/", include("apps.about.urls"), name='about'),
    path("", include("apps.landing.urls")),
]

# for online static
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

class CustomUserManager(BaseUserManager):
    def create_user(self, username, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        extra_fields.setdefault('is_active', True)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(username, email, password, **extra_fields)

class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=30, unique=True)
    email = models.EmailField(max_length=255, unique=True)
    first_name = models.CharField(max_length=30, blank=True)
    surname = models.CharField(max_length=30, blank=True)
    phone = models.CharField(max_length=15, blank=True)
    profile_image = models.ImageField(upload_to='profile_images/', blank=True, null=True)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def get_full_name(self):
        if self.first_name and self.surname:
            return f"{self.first_name} {self.surname}"
        return self.username  # Fallback to the username
    
    def __str__(self):
        return self.username

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    profile_image = models.ImageField(upload_to='profile_images/', blank=True, null=True)
    first_name = models.CharField(max_length=30, blank=True)
    surname = models.CharField(max_length=30, blank=True)
    phone = models.CharField(max_length=15, blank=True)

    def __str__(self):
        return self.user.username

apps/accounts/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import CustomUser

class UserRegisterForm(UserCreationForm):
    """Only for user registration"""
    email = forms.EmailField()

    class Meta:
        model = CustomUser  
        fields = ['username','email','password1','password2']

class ProfileUpdateForm(forms.ModelForm):
    """Update fileds once user is already registered, except username"""
    class Meta:
        model = CustomUser
        fields = ['profile_image', 'first_name', 'surname', 'phone']

class ProfileUsernameForm(UserCreationForm):
    """Update just username, to prevent saving error of username already in use"""
    class Meta:
        model = CustomUser  
        fields = ['username','password1','password2']

class EmailUpdateForm(forms.Form):
    new_email = forms.EmailField()

apps/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm
from django.contrib.auth.decorators import login_required
from .forms import ProfileUpdateForm, ProfileUsernameForm
from .models import Profile
from django.contrib.auth import login
from .forms import EmailUpdateForm
from django.db.models import Q
from apps.store.models import Customer
from django.contrib.auth import views as auth_views


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get("username")
            email = form.cleaned_data.get("email")

            # Check if the user has a customer profile
            if hasattr(user, 'customer'):
                customer = user.customer
                print("requested customer:",customer)
            else:
                # If not, create a Customer object for the user
                customer = Customer(user=user, name=username, email=email)
                customer.save()
                print("new customer:",customer)

            login(request, user)
            messages.success(
                request, f"Hi {username}, your account was created successfully"
            )

            return redirect("/")
    else:
        form = UserRegisterForm()

    return render(request, "accounts/authentication/register.html", {"form": form})


class CustomLoginView(auth_views.LoginView):
    def form_valid(self, form):
        response = super().form_valid(form)

        if self.request.user.is_authenticated:
            # Check if the user has a customer profile
            if hasattr(self.request.user, 'customer'):
                customer = self.request.user.customer
                print("Requested customer:", customer)
            else:
                # If not, create a Customer object for the user
                customer = Customer(user=self.request.user, name=self.request.user.username, email=self.request.user.email)
                customer.save()
                print("New customer:", customer)

        # Use the 'next' parameter to redirect users to the intended page after login
        next_url = self.request.GET.get('next')
        if next_url:
            return redirect(next_url)

        return response
    
# def logout(request):  // no need to, same as above
# here we use just a template login and a url: in urls.py
# from django.contrib.auth import views as auth_view




@login_required
def profile(request):
    return render(request, "accounts/authentication/profile.html")


@login_required
def profile_update(request):
    """Request user and user Profile, if does not exist, create one
    based on Profile model that takes user. Combines UserRegisterForm and
    ProfileUpdateForm, if the form has changed save, alert, redirect."""
    user = request.user
    try:
        profile = user.profile
    except Profile.DoesNotExist:
        profile = Profile(user=user)

    if request.method == "POST":
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=user)

        if profile_form.is_valid():
            profile_form_has_changed = profile_form.has_changed()
            login(request, user)

            if profile_form_has_changed:
                profile_form.save()

                messages.success(request, "Your profile has been updated.")
            else:
                messages.info(request, "No changes were made to your profile.")

            return redirect("profile")
        else:
            messages.error(request, "Please correct the errors below.")

    else:
        profile_form = ProfileUpdateForm(instance=profile)

    return render(
        request, "accounts/update/profile_update.html", {"profile_form": profile_form}
    )


@login_required
def profile_update_username(request):
    user = request.user
    if request.method == "POST":
        user_form = ProfileUsernameForm(request.POST, instance=request.user)
        if user_form.is_valid():
            user_form.save()
            login(request, user)
            messages.success(request, "Your username has been updated.")
            return redirect("profile")
        else:
            messages.error(request, "Please correct the errors below.")
    else:
        user_form = ProfileUsernameForm(instance=request.user)

    return render(
        request, "accounts/update/profile_update_username.html", {"user_form": user_form}
    )


@login_required
def email_update(request):
    user = request.user
    if request.method == "POST":
        email_form = EmailUpdateForm(request.POST)

        if email_form.is_valid():
            new_email = email_form.cleaned_data["new_email"].lower()
            request.user.email = new_email
            request.user.save()
            login(request, user)
            messages.success(request, "Your email address has been updated.")
            return redirect("profile")
        else:
            messages.error(request, "Please correct the errors below.")
    else:
        email_form = EmailUpdateForm()

    return render(request, "accounts/update/email_update.html", {"email_form": email_form})


from django.http import HttpResponseForbidden
from django.contrib.auth import get_user_model


def is_staff_or_admin(view_func):
    """Custom decorator: for manage_staff_users view"""

    def _wrapped_view(request, *args, **kwargs):
        if request.user.is_staff or request.user.is_superuser:
            return view_func(request, *args, **kwargs)
        else:
            return HttpResponseForbidden(
                "Access denied. You must be a staff member or administrator to access this page."
            )

    return _wrapped_view


@login_required
@is_staff_or_admin
def manage_staff_users(request):
    User = get_user_model()
    search_query = request.GET.get("q")

    if search_query:
        search_results = User.objects.filter(
            Q(username__icontains=search_query)
            | Q(email__icontains=search_query)
            | Q(first_name__icontains=search_query)
            | Q(surname__icontains=search_query)
        )
    else:
        # If no search query, fetch all users
        search_results = User.objects.all()

    if not search_results:
        message = "No search results found."

    return render(
        request,
        "accounts/admin_and_staff/manage_staff_users.html",
        {"users": search_results, "message": message if not search_results else ""},
    )

templates/accounts/authentication/login.html
{% extends "base.html" %}
{% block head_title %}Login{% endblock head_title %}<!--Alt + 0149-->
{% load static %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block content %}

    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <div class="container" style="margin-top: 30px;">
    <form action="" method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
          <legend class="border-bottom mb-4">Sing In Now</legend>
          {{ form|crispy }}
      </fieldset>
      <div class="form-group" id="signup-button">
          <button class="btn btn-info">Sign In</button>
      </div>
      <div class="form-group">
          <small class="text-muted ml-3" >Don't have an account yet? <a href="{% url 'register' %}">Sign Up</a></small>
      </div>
    </form>
    <div class="form-group">
        <small class="text-muted ml-3">Forgotten your password? <a href="{% url 'reset_password' %}">Reset it</a></small>
    </div>
    
    </div>

{% endblock %}

templates/accounts/authentication/logout.html
{% extends "base.html" %}
{% block head_title %}Logged out{% endblock head_title %}<!--Alt + 0149-->
{% load static %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block content %}

  <div class="container">
    <h1>You have been Logged out</h1>
    <h5><a href="{% url 'login' %}">Login In Again</a></h5>
    <h5><a href="/">Go back Home</a></h5>
  </div>  

{% endblock %}

templates/accounts/authentication/profile.html
{% extends "base.html" %}
{% block head_title %}Profile Details{% endblock head_title %}
{% load crispy_forms_tags %}
{% load static %}
{% load markdown_deux_tags %}


{% block content %}

  <div class="container">
    <div class="profile-header">
      <legend class="border-bottom mb-4 profile-title">Profile Details</legend>
      <a class="edit-profile-link" href="{% url 'profile_update' %}">
        <i class="fas fa-edit"></i> Edit
      </a>
    </div>
    <div class="row align-items-center">
      <div class="col-md-4 col-sm-12 text-center mx-auto"> <!-- Center on small and medium screens -->
        <div class="circular-profile-image shadow circular-shadow">
          {% if user.profile_image %}
          <img src="{{ user.profile_image.url }}" alt="profile image" class="img-fluid rounded-circle" />
          {% else %}
          <div class="default-profile-image text-light">
            <span style="font-size: 100px;">&#128060;</span>
          </div>
          {% endif %}

        </div>
      </div>
      <div class="col-md-8">
        <div class="profile-info">
          <div class="profile-field">
            <h3 class="field-label">Username:</h3>
            <span class="field-value">{{ user.username }}</span>
          </div>
          <div class="profile-field">
            <h3 class="field-label">Email:</h3>
            <span class="field-value">{{ user.email }}</span>
          </div>
          <div class="profile-field">
            <h3 class="field-label">First Name:</h3>
            <span class="field-value">{{ user.first_name }}</span>
          </div>
          <div class="profile-field">
            <h3 class="field-label">Surname:</h3>
            <span class="field-value">{{ user.surname }}</span>
          </div>
          <div class="profile-field">
            <h3 class="field-label">Phone:</h3>
            <span class="field-value">{{ user.phone }}</span>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% if user.is_staff or user.is_superuser %}
  <div class="container mt-4">
    <legend class="border-bottom mb-4">Admin panel</legend>
    <ul>
        <li><a href="{% url 'accounts:manage_staff_users' %}" target="_blank">Manage / Create Staff users</a></li>
      </ul>
    </div>
  {% endif %}
  
{% endblock content %}

templates/accounts/authentication/register.html
{% extends "base.html" %}
{% block head_title %}Register{% endblock head_title %}<!--Alt + 0149-->

{% load static %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block content %}

    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <div class="container" style="margin-top: 30px;">
    <form action="" method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
          <legend class="border-bottom mb-4">Join Now</legend>
          {{ form|crispy }}
      </fieldset>
      <div class="form-group" id="signup-button">
          <button class="btn btn-info">Sign Up</button>
      </div>
      <div class="form-group">
          <small class="text-muted ml-3" >Already have an account? <a href="{% url 'login' %}">Sign In</a></small>
      </div>
    </form>
    </div>

{% endblock %}