apps/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    # pages
    path('', views.about, name='about'),
   
]

apps/courses/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from apps.courses.views import courses_view, course_detail, checkout, payment_failed, payment_success

app_name = 'courses'

urlpatterns = [
    path('', courses_view, name='courses_view'),
    path('<str:slug>/', course_detail, name='course_detail'),
    path('checkout/<str:slug>/', checkout, name='course_checkout'),
    path('checkout/<str:slug>/payment_success', payment_success, name='payment_success'),
    path('checkout/<str:slug>/payment_failed', payment_failed, name='payment_failed'),
    path('', include('paypal.standard.ipn.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.post_list, name='list'),
    path('create/', views.post_create, name='post_create'),
    path('<slug>/', views.post_detail, name='post_detail'),
    path('<slug>/edit/', views.post_update, name='update'),
    path('<slug>/delete/', views.post_delete, name='post_delete'),
    path('<slug>/delete/confirm/', views.post_confirm_delete, name='post_confirm_delete'),
]

apps/store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    # pages
    path('', views.store, name='store'),
    path('cart/', views.cart, name='cart'),
    path('checkout/', views.checkout, name='checkout'),
    
    # endpoints : update_item
    path('cart/update_item/', views.updateItem, name='update_item'),# store JsonResponse +: for template
    path('checkout/update_item/', views.updateItem, name='update_item'),
    path('update_item/', views.updateItem, name='update_item'),

    # endpoints : process_order
    path('process_order/', views.processOrder, name='process_order'),
    path('checkout/process_order/', views.processOrder, name='process_order'),
    path('checkout/update_item/process_order/', views.processOrder, name='process_order'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.accounts import views
from django.contrib.auth import views as auth_view

urlpatterns = [
    # admin panels
    path('admin/', admin.site.urls),
    
    # authentication 
    path("register/", views.register , name='register'),
    path("profile/", views.profile , name='profile'),
    path("profile/manage_staff_users/", include("apps.accounts.urls"), name="manage_staff_users"),
    path("profile/update", views.profile_update , name='profile_update'),
    path('profile/update/username/', views.profile_update_username, name='profile_update_username'),
    path('email_update/', views.email_update, name='email_update'),
    path("login/", views.CustomLoginView.as_view(template_name='accounts/authentication/login.html'), name='login'),
    path("logout/", auth_view.LogoutView.as_view(template_name='accounts/authentication/logout.html'), name='logout'),
    
    # reset password
    path('reset_password/',auth_view.PasswordResetView.as_view(template_name='accounts/password_reset/reset_password.html'),name='reset_password'),
    path('reset_password_sent/',auth_view.PasswordResetDoneView.as_view(template_name='accounts/password_reset/reset_password_sent.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_view.PasswordResetConfirmView.as_view(template_name='accounts/password_reset/reset_password_confirm.html'),name='password_reset_confirm'),
    path('reset_password_complete/',auth_view.PasswordResetCompleteView.as_view(template_name='accounts/password_reset/reset_password_complete.html'),name='password_reset_complete'),

    # apps
    path("comments/", include("apps.comments.urls")),
    path("posts/", include("apps.posts.urls"), name='posts'),
    path("store/", include("apps.store.urls"), name='store'),
    path("courses/", include("apps.courses.urls"), name='courses_view'),
    path("about/", include("apps.about.urls"), name='about'),
    path("", include("apps.landing.urls")),
]

# for online static
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
{% load crispy_forms_tags %} 
{% load markdown_deux_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block head_title %}Blog • Posts{% endblock head_title %}</title>

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

    <!-- marked -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/8.0.0/marked.min.js" integrity="sha512-BXVL0B4hjclkEj5vS1KjYncDRB7XHVAUFb/j8oaOZMTVK38R6hj6ZQsLCuijQyuN73ECpNrlc7YEC2cbfxOoLg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <!-- Showdown library -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/showdown/1.9.1/showdown.min.js"></script>

    <!-- CSRFToken -->
    <script>
      var csrftoken = '{{ csrf_token }}';
    </script>

    <!-- Get Cookie -->
    <script>

      function getCookie(name) {
        var cookieArr = document.cookie.split(";")

        for(var i  = 0; i < cookieArr.lenght; i++) {
          var cookiePair = cookieArr[i].split("=");

          if(name == cookiePair[0].trim()){
            return decodeURIComponent(cookiePair[1]);
          }
        }

        return null;
    }
    var cart = JSON.parse(getCookie('cart'))
    
    if (cart == undefined){
      cart = {}
      console.log('Cart Created!', cart)
      document.cookie = 'cart'+ JSONstringify(cart) + ";domain=;path=/"
    }
    console.log("Cart:", cart)
   </script>

   
   
    <script>
        $(document).ready(function () {
         //-- JQ function: apply Jquery function Markdown HTML
            // Create a Showdown converter instance
            var converter = new showdown.Converter();
            

            // @@ preview: Function to update the preview============================
            function updatePreview() {
                // Get the values from the form fields
                var title = $("#id_title").val();
                var content = $("#wmd-input-real-time-content").val();
        
                // Render Markdown content to HTML using Showdown, instead of marked
                var htmlContent = converter.makeHtml(content);

                // Replace newline characters with <br> tags in the HTML content
                htmlContent = htmlContent.replace(/\n/g, '<br>');
        
                // Update the preview elements
                $("#preview-title").text(title);
                $("#preview-content").html(htmlContent);
            }
        
            // preview: trigger the preview update on forms
            $("#id_title, #wmd-input-real-time-content").on("keyup change", updatePreview);
        
            // preview: Call the updatePreview() function initially
            updatePreview();
        });
    </script>
    

    <!--load user var js-->
    <script type='text/javascript'>
      {% with user_username=request.user.username %}
        var user = '{{ user_username }}';
      {% endwith %}
    </script>



    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    
    <!-- css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'accounts/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'comments/post_detail/css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'comments/comment_thread/css/main.css' %}">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'fontawesome-free/css/all.min.css' %}">
    <script src="https://kit.fontawesome.com/98d1538458.js" crossorigin="anonymous"></script>

    {% block head_extra %} {% endblock head_extra%} <!--for post_form-->
</head>

<body>
    <!-- Facebook Comments --> 
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/es_LA/sdk.js#xfbml=1&version=v17.0" nonce="V5HI9YZM"></script>

    <!-- Load Facebook SDK for JavaScript -->
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" 
            src="https://connect.facebook.net/en_US/sdk.js#xfbml=1
             &version={graph-api-version}
             &appId={your-facebook-app-id}
             &autoLogAppEvents=1" 
        nonce="FOKrbAYI">
  </script>
  
  {% include "messages_display.html" %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <!-- Your logo or brand here -->

      {% comment %} <a class="navbar-brand" href="">
        <!-- Insert your logo or brand image here -->
      </a> {% endcomment %}
  
      <!-- Navbar Toggler Button -->
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <!-- Navbar Items -->
      <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
        <ul class="navbar-nav ms-auto" style="font-size:24px">
          <li class="nav-item">
            <a class="nav-link active" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'posts:list' %}">Blog</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'about:about' %}">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'courses:courses_view' %}">Courses</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'store:store' %}">Store</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'store:cart' %}">
                <div class="cart-badge">
                    <i class="fas fa-shopping-cart"></i>
                    <span id="cart-total">{{ cart_count }}</span>
                </div>
            </a>
          </li>               
        </ul>


        <!-- Authenticated User Links -->
        <div class="justify-content-end ms-auto">
            {% if not request.user.is_authenticated %}
            <ul class="navbar-nav">
                <li class="nav-item btn btn-outline-info me-2">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
                <li class="nav-item btn btn-outline-primary">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav">
                <li class="nav-item btn btn-outline-info">
                    <a class="nav-link " href="{% url 'logout' %}">Logout</a>
                </li>
                <li class="nav-item btn ms-lg-3">
                  {% if request.user.is_staff or request.user.is_superuser %}
                  <div class="dropdown">
                      <a class="nav-link dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          <i class="fas fa-plus"></i> <!-- This is the plus icon -->
                      </a>
                      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                          <a class="dropdown-item" href="{% url 'posts:post_create' %}">Create New Post</a>
                          <a class="dropdown-item" href="#">Add / Manage Store Item</a>
                          <!-- Add more dropdown items as needed -->
                      </div>
                  </div>
                  {% endif %}
              </li>
                <li class="nav-item btn ms-lg-3">
                  <a class="nav-link" href="{% url 'profile' %}">
                      {% if user.profile_image %}
                          <img src="{{ user.profile_image.url }}" alt="Profile Image" class="rounded-circle cover" width="30" height="30">
                      {% else %}
                          <i class="fas fa-user"></i>
                      {% endif %}
                  </a>
                </li>
            </ul>
            {% endif %}
        </div>
      </div>
    </div>
  </nav>
  












<div class="container mt-4">
    {% block content %}{% endblock %}
</div>
</body>
</html>

templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %} 
{% load markdown_deux_tags %}

{% block content %}

    <div class='col-sm-6 col-sm-offset-3 pt-3'>
        <h2>{{ title }}</h2>
        <hr/>

        <form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
            <!-- {{ form.as_p }}  -->
            {{ form|crispy }} 
            <input type='submit' value='{{ title }}'/>
        </form>
    </div>
{% endblock content %}

templates/home.html
{% extends "base.html" %}
{% block head_title %}Home{% endblock head_title %}
{% load crispy_forms_tags %} 
{% load markdown_deux_tags %}

{% block content %}
{% if user.is_authenticated %}
  <h1>Hello, welcome back! {% if user.first_name %}{{ user.first_name }}{% else %}{{ user.username }}{% endif %}</h1>
{% else %}
  <p>Welcome to the landing page.</p>
{% endif %}
{% endblock content %}

templates/messages_display.html
{% if messages %}
    <div class="messages">
        <ul class='messages'>
            {% for message in messages %}
             <div class="alert alert-{{message.tags}}">{{message}}</div>
            {% endfor %}
        </ul>
    </div>
{% endif %}