apps/courses/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from apps.courses.views import courses_view, course_detail, checkout, payment_failed, payment_success

app_name = 'courses'

urlpatterns = [
    path('', courses_view, name='courses_view'),
    path('<str:slug>/', course_detail, name='course_detail'),
    path('checkout/<str:slug>/', checkout, name='course_checkout'),
    path('checkout/<str:slug>/payment_success', payment_success, name='payment_success'),
    path('checkout/<str:slug>/payment_failed', payment_failed, name='payment_failed'),
    path('', include('paypal.standard.ipn.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.accounts import views
from django.contrib.auth import views as auth_view

urlpatterns = [
    # admin panels
    path('admin/', admin.site.urls),
    
    # authentication 
    path("register/", views.register , name='register'),
    path("profile/", views.profile , name='profile'),
    path("profile/manage_staff_users/", include("apps.accounts.urls"), name="manage_staff_users"),
    path("profile/update", views.profile_update , name='profile_update'),
    path('profile/update/username/', views.profile_update_username, name='profile_update_username'),
    path('email_update/', views.email_update, name='email_update'),
    path("login/", views.CustomLoginView.as_view(template_name='accounts/authentication/login.html'), name='login'),
    path("logout/", auth_view.LogoutView.as_view(template_name='accounts/authentication/logout.html'), name='logout'),
    
    # reset password
    path('reset_password/',auth_view.PasswordResetView.as_view(template_name='accounts/password_reset/reset_password.html'),name='reset_password'),
    path('reset_password_sent/',auth_view.PasswordResetDoneView.as_view(template_name='accounts/password_reset/reset_password_sent.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_view.PasswordResetConfirmView.as_view(template_name='accounts/password_reset/reset_password_confirm.html'),name='password_reset_confirm'),
    path('reset_password_complete/',auth_view.PasswordResetCompleteView.as_view(template_name='accounts/password_reset/reset_password_complete.html'),name='password_reset_complete'),

    # apps
    path("comments/", include("apps.comments.urls")),
    path("posts/", include("apps.posts.urls"), name='posts'),
    path("store/", include("apps.store.urls"), name='store'),
    path("courses/", include("apps.courses.urls"), name='courses_view'),
    path("about/", include("apps.about.urls"), name='about'),
    path("", include("apps.landing.urls")),
]

# for online static
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/courses/models.py
from django.db import models

apps/courses/models/course.py
from django.db import models


class Course(models.Model):
    name = models.CharField(max_length= 50, null= False)
    slug = models.CharField(max_length= 50, null= False, unique= True)
    description = models.CharField(max_length= 200, null= True)
    price = models.IntegerField(null= False, default= 0)
    discount = models.IntegerField(null= False, default= 0)
    active = models.BooleanField(default= False)
    thumbnail = models.ImageField(upload_to="files/thumbnail")
    date = models.DateTimeField(auto_now_add= True) #editable
    resource = models.FileField(upload_to="files/resource")
    lenght = models.IntegerField(null= False)

    def __str__(self):
        return self.name

class CourseProperty(models.Model):
    description = models.CharField(max_length= 100, null= False)
    course = models.ForeignKey(Course, null= False, on_delete=models.CASCADE)

    class Meta: # defines a way of how an instance of a class is build. Changes the behavior of the model
        abstract = True

class Tag(CourseProperty):
    pass

class Prerequisite(CourseProperty):
    pass

class Learning(CourseProperty):
    pass

apps/courses/models/payment.py
from django.db import models
from django.conf import settings
from .course import Course
from .user_course import UserCourse

class Payment(models.Model):
    order_id = models.CharField(max_length=50, null=False)
    payment_id = models.CharField(max_length=50)
    user_course= models.ForeignKey(UserCourse, null=True, blank=True, on_delete=models.CASCADE, related_name='payments_for_user_courses')
    user= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, null=False, on_delete=models.CASCADE)
    date= models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)

    def __str__(self):
        return f'order_id: {self.order_id}'

apps/courses/models/user_course.py
from django.db import models
from django.conf import settings
from .course import Course

class UserCourse(models.Model):
    course = models.ForeignKey(Course, null=False, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, null=False, on_delete=models.CASCADE, related_name='user_courses_for_course') #superadmin default
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.username} - {self.course.name}'

apps/courses/models/video.py
from django.db import models
from .course import Course

class Video(models.Model):
    title = models.CharField(max_length=100, null=False)
    course = models.ForeignKey(Course, null=False, on_delete=models.CASCADE)
    serial_number = models.IntegerField(null= False) # to be shareable from yt
    video_id = models.CharField(max_length=100, null=False)
    is_preview = models.BooleanField(default= False)

    def __str__(self):
        return self.title

apps/courses/views.py
from django.shortcuts import render

# Create your views here.
# def courses_view(request):
#     return render (request, 'courses/courses.html')

apps/courses/views/checkout.py
from django.shortcuts import render,redirect
from apps.courses.models import Course
from django.contrib import messages
from urllib.parse import urlencode
from django.urls import reverse
from paypal.standard.forms import PayPalPaymentsForm
from django.conf import settings
import uuid

def checkout(request, slug):
    course = Course.objects.get(slug=slug)
    # Calculate the amount with the discount applied
    amount = course.price - (course.price * (course.discount / 100))

    # Process the enrollment and payment with PayPal integration here
    # ...

    # ↓ login before enrolling
    if not request.user.is_authenticated:
        messages.info(request, "You must be logged in to see more.")
        # Construct the URL for the login page with the 'next' parameter
        login_url = reverse('login')  # Replace 'login' with your login URL name
        next_param = urlencode({'next': request.get_full_path()})
        redirect_url = f'{login_url}?{next_param}'
        return redirect(redirect_url)
    # ☻↓ if enrolled you can see the video...

    # ☻↓ request domain: x.com
    host = request.get_host()

    # ☻↓ prepare checkout course info  
    paypal_checkout = {
        'business': settings.PAYPAL_RECEIVER_EMAIL,
        'amount': amount, # Assign the calculated amount with the discount
        'item_name': course.name,
        'invoice': uuid.uuid4(), #generate random id
        'currency_code': 'USD',
        'notify_url':  f"https://{host}{reverse('paypal-ipn')}",# send payment req to this endpoin inside library django-paypal
        'return_url': f"https://{host}{reverse('payment_success', kwargs={'slug':course.slug})}",
        'cancel_url': f"https://{host}{reverse('payment_failed', kwargs={'slug':course.slug})}",
    }

    # comes from library import
    paypal_payment = PayPalPaymentsForm(initial=paypal_checkout)

    context = {
        'course' : course,
        'paypal' : paypal_payment,
        # Add more context data as needed 
    }
    return render(request, 'courses/checkout/checkout.html', context=context)

apps/courses/views/courses.py
from django.shortcuts import render,redirect
from apps.courses.models import Course, Video
from django.contrib import messages
from urllib.parse import urlencode
from django.urls import reverse

# Create your views here.
def courses_view(request):
    courses = Course.objects.all()
    return render (request, 'courses/courses.html', context={"courses":courses})

def course_detail(request, slug):
    course = Course.objects.get(slug=slug)
    serial_number = request.GET.get('lecture')#from searchbar after click on lecture
    if serial_number is None : # for lecture [0]
        serial_number = 1
    videos = course.video_set.all().order_by("serial_number")
    # ↓ return course and video lecture from video Model serial_number from Yt when uploading 
    # ↓ then ask it in frontend passing video_id to player and each video has it's {{video.serial_number}}">{{video}} 
    video = Video.objects.get(serial_number = serial_number, course = course)
    print(serial_number, video)
    print("Preview video", video.is_preview)
    # ↓ login to see if enrolled when clicking see more
    # ↓ after login go back to course to see videos
    if ((request.user.is_authenticated is False) and (video.is_preview is False)):
        messages.info(request, "You must be logged in to see more.")
        # Construct the URL for the login page with the 'next' parameter
        login_url = reverse('login')  # Replace 'login' with your login URL name
        next_param = urlencode({'next': request.get_full_path()})
        redirect_url = f'{login_url}?{next_param}'
        return redirect(redirect_url)

    # if enrolled you can see any video...

    context = {
        'course' : course,
        'video': video,
        'videos': videos,
    }
    return render(request, 'courses/course_detail.html', context=context)

apps/courses/views/payment.py
from django.shortcuts import render,redirect
from apps.courses.models import Course
from django.contrib import messages
from urllib.parse import urlencode
from django.urls import reverse

def payment_success(request, slug):
    course = Course.objects.get(slug=slug)
    context = {
        'course' : course,
        # Add more context data as needed
    }
    return render(request, 'courses/payment/payment_success.html', context=context)

def payment_failed(request, slug):
    course = Course.objects.get(slug=slug)
    context = {
        'course' : course,
        # Add more context data as needed
    }
    return render(request, 'courses/payment/payment_failed.html', context=context)

templates/courses/checkout.html
{% extends "base.html" %}
{% block head_title %}♣ Courses • Checkout{% endblock head_title %}<!--Alt + 0149-->
{% load static %}
{% load urlify %}
{% load crispy_forms_tags %}
{% load course_custom_tags %}

{% block content %}
<h1 class="display-4 alert border text-center">Checkout</h1>
<hr>
<h1 class="text-center">You are going to enroll:</h1>
<ul>
    <li>Course Name: <strong>{{course.name}}</strong></li>
    <li>Description: {{course.description}}</li>
    <li>Course price: {{course.price|money_sign}}</li>
    <li>Discount: {{course.discount}}%</li>
    <p><strong>Total: {% cal_sellprice course.price course.discount as value %}{{value|money_sign}}</strong></p>
</ul>
<hr>
<div class="justify-content-center align-items-center  text-center">
    <form action="/login/" method="post">
        {% csrf_token %}

        <input type="submit" value="Checkout" >
    </form>
</div>
{% endblock %}

templates/courses/course_detail.html
{% extends "base.html" %}
{% block head_title %}Course • {{course.name}}{% endblock head_title %}<!--Alt + 0149-->
{% load static %}
{% load urlify %}
{% load crispy_forms_tags %}
{% load course_custom_tags %}

{% block content %}

    <div class="container-fluid">
        
        <div class="hidden">

            <h1 class='display-1'>{{course.name}}</h1>
            <p>{{course.description}}</p>
            <p>{{course.tag_set.all}}</p><!--tag_set[Tag]-->
            <div class='price-block'>
                {% if course.discount > 0 %}
                    Save {{course.discount}}%
                {% endif %}
                <span class='price'>
                    {% if course.discount > 0 %}
                    || <del>{{course.price|money_sign}}</del>
                    →&nbsp; 
                    {% endif %}
                    <span>{% cal_sellprice course.price course.discount as value %}{{value|money_sign}} </span>
                </span>
            </div>
            <br>
            <p>{{course.video_set.all}}</p><!--video_set[Video]-->
            <p>{{course.prerequisite_set.all}}</p><!--prerequisite_set[prerequisite]-->
            <p>{{course.learning_set.all}}</p><!--learning_set[learning]-->
        </div>

        <!-- VideoPlayer  -->
        <br>
        <div class="card p-3">
            <div class="row">
                <div class="col">
                    <div class="mx-auto">
                        <iframe id="player" class="mx-auto" width="100%" height="315" src="https://www.youtube.com/embed/{{video.video_id}}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
                    </div>
                </div>

                <!-- Video List -->
                <div class="col-3">
                        <ul id="video_list"  class="list-group">
                            {% for v in videos %}<!-- comes sorted from backend-->
                            <!-- ↓ href brought from backend serial_number from each video_id--> 
                            <li class="list-group-item 
                                       {% if v == video %} active-video {% endif %}">
                                <a href="?lecture={{v.serial_number}}">
                                    {{v}}
                                </a>
                            </li>
                            {% endfor %}
                        </ul>
                </div>
            </div>
        </div>
        <!-- VideoPlayer-Modules end -->

        <!-- Prerequisites -->
        <div class="mt-3">
            <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Prerequisite:</h5>
                  <h6 class="card-text mb-2 text-body-secondary">
                    {% for pre in course.prerequisite_set.all %}
                    <ol>
                        <li class="">{{pre.description}}</li>
                    </ol>
                    {% endfor %}
                  </h6>
                  {% comment %} <p class="card-text"></p> {% endcomment %}
                  <a href="#" class="card-link">Card link</a>
                  <a href="#" class="card-link">Another link</a>
                </div>
              </div>
        </div>
        <!-- Prerequisites end -->

        <!--  Learnings  -->
        <div class="mt-3">
            <div class="card">
                <div class="card-body">
                  <h5 class="card-title">Learnings:</h5>
                  <h6 class="card-text mb-2 text-body-secondary">
                    {% for lea in course.learning_set.all %}
                    <ol>
                        <li class="">{{lea.description}}</li>
                    </ol>
                    {% endfor %}
                  </h6>
                  <a href="#" class="card-link">Card link</a>
                  <a href="#" class="card-link">Another link</a>
                </div>
              </div>
        </div>

        <!--  Learnings end -->
        <br>
        <br>
        <br>
    </div>



<script src="{% static 'courses/js/course_detail.js' %}"></script>
<link rel="stylesheet" href="{% static 'courses/css/scrollbar.css' %}">
<link rel="stylesheet" href="{% static 'courses/css/common.css' %}">

{% endblock %}

templates/courses/courses.html
{% extends "base.html" %}
{% block head_title %}♣ Courses{% endblock head_title %}<!--Alt + 0149-->
{% load static %}
{% load urlify %}
{% load crispy_forms_tags %}
{% load course_custom_tags %}

{% block content %}

<style>
    .price {
        font-size:20px;
    }
</style>

<div class="container-fluid">
    <br>
    <div class="row">
        {% for course in courses %}
            <div class="col mx-auto">
                <div class="card mx-auto" style="width: 18rem;">
                    <img src="{{course.thumbnail.url}}" class="card-img-top" alt="{{course.thumbnail}}">
                    <div class="card-body">
                        <h5 class="card-title">{{course.name}}</h5>
                        <p>{{course.description}}</p>
                        <p class="card-text m-0 p-0">
                            {% if course.discount > 0 %}
                                Save {{course.discount}}%
                                <br>
                            {% endif %}
                            <span class='price'>
                                {% if course.discount > 0 %}
                                <del>{{course.price|money_sign}}</del>
                                &nbsp;
                                {% endif %}
                            <span>{% cal_sellprice course.price course.discount as value %}{{value|money_sign}} </span>
                            </span>
                            
                        </p>

                    </div>
                    <div class="card-footer p-0">
                        <div class="row mx-0">
                            <div class="col border-right">
                                <a href="{% url 'courses:course_checkout' slug=course.slug %}" class="btn btn-light btn-block">Enroll Now</a>
                            </div>
                            <div class="col">
                                <a href="{% url 'courses:course_detail' slug=course.slug %}" class="btn btn-light btn-block">Show More</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}